use rtf_parser::{
    Block, Diagnostic, DocumentModel, FontDef, ImageFormat, ImageResource, LineSpacing,
    PageGeometry, ParagraphAlign, ParagraphStyle, Run, TextStyle,
};
use ts_rs::TS;

fn main() {
    let config = ts_rs::Config::default();
    println!("// Generated by cargo run -p rtf-parser --example generate_types. Do not edit.");
    println!();
    for declaration in [
        PageGeometry::decl(&config),
        FontDef::decl(&config),
        ParagraphAlign::decl(&config),
        LineSpacing::decl(&config),
        TextStyle::decl(&config),
        ParagraphStyle::decl(&config),
        Run::decl(&config),
        Block::decl(&config),
        ImageFormat::decl(&config),
        ImageResource::decl(&config),
        Diagnostic::decl(&config),
        DocumentModel::decl(&config),
    ] {
        println!("export {declaration}");
    }
}
