use rtf_parser::{
    Block, Border, BorderStyle, CellBorders, CellShading, Diagnostic, DocumentModel, FontDef,
    ImageFormat, ImageResource, LineSpacing, Padding, PageGeometry, ParagraphAlign, ParagraphStyle,
    RowAlign, RowHeight, Run, TableCell, TextStyle, VerticalAlign,
};
use std::env;
use std::fmt::Write as _;
use std::fs;
use std::io;
use std::path::Path;
use ts_rs::TS;

fn declarations() -> String {
    let config = ts_rs::Config::default();
    let mut output = String::from(
        "// Generated by cargo run -p rtf-parser --example generate_types. Do not edit.\n\n",
    );
    for declaration in [
        PageGeometry::decl(&config),
        FontDef::decl(&config),
        ParagraphAlign::decl(&config),
        LineSpacing::decl(&config),
        TextStyle::decl(&config),
        ParagraphStyle::decl(&config),
        Run::decl(&config),
        RowAlign::decl(&config),
        RowHeight::decl(&config),
        BorderStyle::decl(&config),
        Border::decl(&config),
        CellBorders::decl(&config),
        Padding::decl(&config),
        VerticalAlign::decl(&config),
        CellShading::decl(&config),
        TableCell::decl(&config),
        Block::decl(&config),
        ImageFormat::decl(&config),
        ImageResource::decl(&config),
        Diagnostic::decl(&config),
        DocumentModel::decl(&config),
    ] {
        writeln!(output, "export {declaration}").expect("writing to a String cannot fail");
    }
    output
}

fn main() -> Result<(), Box<dyn std::error::Error>> {
    let output = declarations();
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("../../packages/rtf-viewer/src/generated/model.ts");

    match env::args().nth(1).as_deref() {
        None => print!("{output}"),
        Some("--write") => fs::write(path, output)?,
        Some("--check") => {
            if fs::read_to_string(path)? != output {
                return Err(io::Error::other(
                    "Generated model has drifted. Run pnpm generate:types.",
                )
                .into());
            }
            println!("Rust/TypeScript contract matches.");
        }
        Some(argument) => {
            return Err(io::Error::new(
                io::ErrorKind::InvalidInput,
                format!("unknown argument {argument:?}; expected --write or --check"),
            )
            .into());
        }
    }

    Ok(())
}
